# UFTP Transfer Configuration for Dunkelflaute Analysis
# Transfer tsr (solar radiation) files for TCo1279-DART-1950C
# Source: Aleph /scratch/awicm3/TCo1279-DART-1950C/outdata/oifs
# Destination: Levante /work/ab0995/ICCP_AWI_hackthon_2025/TCo1279-DART-1950C/outdata/oifs
# Years: 1950-1969
# Variable: tsr
# Generated: Mon Dec 15 14:17:09 CET 2025

transfers:
  - name: "TCo1279-DART-1950C tsr 1950-1969 from aleph"
    local_base: "/scratch/awicm3/TCo1279-DART-1950C/outdata/oifs"
    remote_dir: "/work/ab0995/ICCP_AWI_hackthon_2025/TCo1279-DART-1950C/outdata/oifs"
    files:
      # 1950
      - "atm_reduced_3h_tsr_3h_195001-195001.nc"
      - "atm_reduced_3h_tsr_3h_195002-195002.nc"
      - "atm_reduced_3h_tsr_3h_195003-195003.nc"
      - "atm_reduced_3h_tsr_3h_195004-195004.nc"
      - "atm_reduced_3h_tsr_3h_195005-195005.nc"
      - "atm_reduced_3h_tsr_3h_195006-195006.nc"
      - "atm_reduced_3h_tsr_3h_195007-195007.nc"
      - "atm_reduced_3h_tsr_3h_195008-195008.nc"
      - "atm_reduced_3h_tsr_3h_195009-195009.nc"
      - "atm_reduced_3h_tsr_3h_195010-195010.nc"
      - "atm_reduced_3h_tsr_3h_195011-195011.nc"
      - "atm_reduced_3h_tsr_3h_195012-195012.nc"
      # 1951
      - "atm_reduced_3h_tsr_3h_195101-195101.nc"
      - "atm_reduced_3h_tsr_3h_195102-195102.nc"
      - "atm_reduced_3h_tsr_3h_195103-195103.nc"
      - "atm_reduced_3h_tsr_3h_195104-195104.nc"
      - "atm_reduced_3h_tsr_3h_195105-195105.nc"
      - "atm_reduced_3h_tsr_3h_195106-195106.nc"
      - "atm_reduced_3h_tsr_3h_195107-195107.nc"
      - "atm_reduced_3h_tsr_3h_195108-195108.nc"
      - "atm_reduced_3h_tsr_3h_195109-195109.nc"
      - "atm_reduced_3h_tsr_3h_195110-195110.nc"
      - "atm_reduced_3h_tsr_3h_195111-195111.nc"
      - "atm_reduced_3h_tsr_3h_195112-195112.nc"
      # 1952
      - "atm_reduced_3h_tsr_3h_195201-195201.nc"
      - "atm_reduced_3h_tsr_3h_195202-195202.nc"
      - "atm_reduced_3h_tsr_3h_195203-195203.nc"
      - "atm_reduced_3h_tsr_3h_195204-195204.nc"
      - "atm_reduced_3h_tsr_3h_195205-195205.nc"
      - "atm_reduced_3h_tsr_3h_195206-195206.nc"
      - "atm_reduced_3h_tsr_3h_195207-195207.nc"
      - "atm_reduced_3h_tsr_3h_195208-195208.nc"
      - "atm_reduced_3h_tsr_3h_195209-195209.nc"
      - "atm_reduced_3h_tsr_3h_195210-195210.nc"
      - "atm_reduced_3h_tsr_3h_195211-195211.nc"
      - "atm_reduced_3h_tsr_3h_195212-195212.nc"
      # 1953
      - "atm_reduced_3h_tsr_3h_195301-195301.nc"
      - "atm_reduced_3h_tsr_3h_195302-195302.nc"
      - "atm_reduced_3h_tsr_3h_195303-195303.nc"
      - "atm_reduced_3h_tsr_3h_195304-195304.nc"
      - "atm_reduced_3h_tsr_3h_195305-195305.nc"
      - "atm_reduced_3h_tsr_3h_195306-195306.nc"
      - "atm_reduced_3h_tsr_3h_195307-195307.nc"
      - "atm_reduced_3h_tsr_3h_195308-195308.nc"
      - "atm_reduced_3h_tsr_3h_195309-195309.nc"
      - "atm_reduced_3h_tsr_3h_195310-195310.nc"
      - "atm_reduced_3h_tsr_3h_195311-195311.nc"
      - "atm_reduced_3h_tsr_3h_195312-195312.nc"
      # 1954
      - "atm_reduced_3h_tsr_3h_195401-195401.nc"
      - "atm_reduced_3h_tsr_3h_195402-195402.nc"
      - "atm_reduced_3h_tsr_3h_195403-195403.nc"
      - "atm_reduced_3h_tsr_3h_195404-195404.nc"
      - "atm_reduced_3h_tsr_3h_195405-195405.nc"
      - "atm_reduced_3h_tsr_3h_195406-195406.nc"
      - "atm_reduced_3h_tsr_3h_195407-195407.nc"
      - "atm_reduced_3h_tsr_3h_195408-195408.nc"
      - "atm_reduced_3h_tsr_3h_195409-195409.nc"
      - "atm_reduced_3h_tsr_3h_195410-195410.nc"
      - "atm_reduced_3h_tsr_3h_195411-195411.nc"
      - "atm_reduced_3h_tsr_3h_195412-195412.nc"
      # 1955
      - "atm_reduced_3h_tsr_3h_195501-195501.nc"
      - "atm_reduced_3h_tsr_3h_195502-195502.nc"
      - "atm_reduced_3h_tsr_3h_195503-195503.nc"
      - "atm_reduced_3h_tsr_3h_195504-195504.nc"
      - "atm_reduced_3h_tsr_3h_195505-195505.nc"
      - "atm_reduced_3h_tsr_3h_195506-195506.nc"
      - "atm_reduced_3h_tsr_3h_195507-195507.nc"
      - "atm_reduced_3h_tsr_3h_195508-195508.nc"
      - "atm_reduced_3h_tsr_3h_195509-195509.nc"
      - "atm_reduced_3h_tsr_3h_195510-195510.nc"
      - "atm_reduced_3h_tsr_3h_195511-195511.nc"
      - "atm_reduced_3h_tsr_3h_195512-195512.nc"
      # 1956
      - "atm_reduced_3h_tsr_3h_195601-195601.nc"
      - "atm_reduced_3h_tsr_3h_195602-195602.nc"
      - "atm_reduced_3h_tsr_3h_195603-195603.nc"
      - "atm_reduced_3h_tsr_3h_195604-195604.nc"
      - "atm_reduced_3h_tsr_3h_195605-195605.nc"
      - "atm_reduced_3h_tsr_3h_195606-195606.nc"
      - "atm_reduced_3h_tsr_3h_195607-195607.nc"
      - "atm_reduced_3h_tsr_3h_195608-195608.nc"
      - "atm_reduced_3h_tsr_3h_195609-195609.nc"
      - "atm_reduced_3h_tsr_3h_195610-195610.nc"
      - "atm_reduced_3h_tsr_3h_195611-195611.nc"
      - "atm_reduced_3h_tsr_3h_195612-195612.nc"
      # 1957
      - "atm_reduced_3h_tsr_3h_195701-195701.nc"
      - "atm_reduced_3h_tsr_3h_195702-195702.nc"
      - "atm_reduced_3h_tsr_3h_195703-195703.nc"
      - "atm_reduced_3h_tsr_3h_195704-195704.nc"
      - "atm_reduced_3h_tsr_3h_195705-195705.nc"
      - "atm_reduced_3h_tsr_3h_195706-195706.nc"
      - "atm_reduced_3h_tsr_3h_195707-195707.nc"
      - "atm_reduced_3h_tsr_3h_195708-195708.nc"
      - "atm_reduced_3h_tsr_3h_195709-195709.nc"
      - "atm_reduced_3h_tsr_3h_195710-195710.nc"
      - "atm_reduced_3h_tsr_3h_195711-195711.nc"
      - "atm_reduced_3h_tsr_3h_195712-195712.nc"
      # 1958
      - "atm_reduced_3h_tsr_3h_195801-195801.nc"
      - "atm_reduced_3h_tsr_3h_195802-195802.nc"
      - "atm_reduced_3h_tsr_3h_195803-195803.nc"
      - "atm_reduced_3h_tsr_3h_195804-195804.nc"
      - "atm_reduced_3h_tsr_3h_195805-195805.nc"
      - "atm_reduced_3h_tsr_3h_195806-195806.nc"
      - "atm_reduced_3h_tsr_3h_195807-195807.nc"
      - "atm_reduced_3h_tsr_3h_195808-195808.nc"
      - "atm_reduced_3h_tsr_3h_195809-195809.nc"
      - "atm_reduced_3h_tsr_3h_195810-195810.nc"
      - "atm_reduced_3h_tsr_3h_195811-195811.nc"
      - "atm_reduced_3h_tsr_3h_195812-195812.nc"
      # 1959
      - "atm_reduced_3h_tsr_3h_195901-195901.nc"
      - "atm_reduced_3h_tsr_3h_195902-195902.nc"
      - "atm_reduced_3h_tsr_3h_195903-195903.nc"
      - "atm_reduced_3h_tsr_3h_195904-195904.nc"
      - "atm_reduced_3h_tsr_3h_195905-195905.nc"
      - "atm_reduced_3h_tsr_3h_195906-195906.nc"
      - "atm_reduced_3h_tsr_3h_195907-195907.nc"
      - "atm_reduced_3h_tsr_3h_195908-195908.nc"
      - "atm_reduced_3h_tsr_3h_195909-195909.nc"
      - "atm_reduced_3h_tsr_3h_195910-195910.nc"
      - "atm_reduced_3h_tsr_3h_195911-195911.nc"
      - "atm_reduced_3h_tsr_3h_195912-195912.nc"
      # 1960
      - "atm_reduced_3h_tsr_3h_196001-196001.nc"
      - "atm_reduced_3h_tsr_3h_196002-196002.nc"
      - "atm_reduced_3h_tsr_3h_196003-196003.nc"
      - "atm_reduced_3h_tsr_3h_196004-196004.nc"
      - "atm_reduced_3h_tsr_3h_196005-196005.nc"
      - "atm_reduced_3h_tsr_3h_196006-196006.nc"
      - "atm_reduced_3h_tsr_3h_196007-196007.nc"
      - "atm_reduced_3h_tsr_3h_196008-196008.nc"
      - "atm_reduced_3h_tsr_3h_196009-196009.nc"
      - "atm_reduced_3h_tsr_3h_196010-196010.nc"
      - "atm_reduced_3h_tsr_3h_196011-196011.nc"
      - "atm_reduced_3h_tsr_3h_196012-196012.nc"
      # 1961
      - "atm_reduced_3h_tsr_3h_196101-196101.nc"
      - "atm_reduced_3h_tsr_3h_196102-196102.nc"
      - "atm_reduced_3h_tsr_3h_196103-196103.nc"
      - "atm_reduced_3h_tsr_3h_196104-196104.nc"
      - "atm_reduced_3h_tsr_3h_196105-196105.nc"
      - "atm_reduced_3h_tsr_3h_196106-196106.nc"
      - "atm_reduced_3h_tsr_3h_196107-196107.nc"
      - "atm_reduced_3h_tsr_3h_196108-196108.nc"
      - "atm_reduced_3h_tsr_3h_196109-196109.nc"
      - "atm_reduced_3h_tsr_3h_196110-196110.nc"
      - "atm_reduced_3h_tsr_3h_196111-196111.nc"
      - "atm_reduced_3h_tsr_3h_196112-196112.nc"
      # 1962
      - "atm_reduced_3h_tsr_3h_196201-196201.nc"
      - "atm_reduced_3h_tsr_3h_196202-196202.nc"
      - "atm_reduced_3h_tsr_3h_196203-196203.nc"
      - "atm_reduced_3h_tsr_3h_196204-196204.nc"
      - "atm_reduced_3h_tsr_3h_196205-196205.nc"
      - "atm_reduced_3h_tsr_3h_196206-196206.nc"
      - "atm_reduced_3h_tsr_3h_196207-196207.nc"
      - "atm_reduced_3h_tsr_3h_196208-196208.nc"
      - "atm_reduced_3h_tsr_3h_196209-196209.nc"
      - "atm_reduced_3h_tsr_3h_196210-196210.nc"
      - "atm_reduced_3h_tsr_3h_196211-196211.nc"
      - "atm_reduced_3h_tsr_3h_196212-196212.nc"
      # 1963
      - "atm_reduced_3h_tsr_3h_196301-196301.nc"
      - "atm_reduced_3h_tsr_3h_196302-196302.nc"
      - "atm_reduced_3h_tsr_3h_196303-196303.nc"
      - "atm_reduced_3h_tsr_3h_196304-196304.nc"
      - "atm_reduced_3h_tsr_3h_196305-196305.nc"
      - "atm_reduced_3h_tsr_3h_196306-196306.nc"
      - "atm_reduced_3h_tsr_3h_196307-196307.nc"
      - "atm_reduced_3h_tsr_3h_196308-196308.nc"
      - "atm_reduced_3h_tsr_3h_196309-196309.nc"
      - "atm_reduced_3h_tsr_3h_196310-196310.nc"
      - "atm_reduced_3h_tsr_3h_196311-196311.nc"
      - "atm_reduced_3h_tsr_3h_196312-196312.nc"
      # 1964
      - "atm_reduced_3h_tsr_3h_196401-196401.nc"
      - "atm_reduced_3h_tsr_3h_196402-196402.nc"
      - "atm_reduced_3h_tsr_3h_196403-196403.nc"
      - "atm_reduced_3h_tsr_3h_196404-196404.nc"
      - "atm_reduced_3h_tsr_3h_196405-196405.nc"
      - "atm_reduced_3h_tsr_3h_196406-196406.nc"
      - "atm_reduced_3h_tsr_3h_196407-196407.nc"
      - "atm_reduced_3h_tsr_3h_196408-196408.nc"
      - "atm_reduced_3h_tsr_3h_196409-196409.nc"
      - "atm_reduced_3h_tsr_3h_196410-196410.nc"
      - "atm_reduced_3h_tsr_3h_196411-196411.nc"
      - "atm_reduced_3h_tsr_3h_196412-196412.nc"
      # 1965
      - "atm_reduced_3h_tsr_3h_196501-196501.nc"
      - "atm_reduced_3h_tsr_3h_196502-196502.nc"
      - "atm_reduced_3h_tsr_3h_196503-196503.nc"
      - "atm_reduced_3h_tsr_3h_196504-196504.nc"
      - "atm_reduced_3h_tsr_3h_196505-196505.nc"
      - "atm_reduced_3h_tsr_3h_196506-196506.nc"
      - "atm_reduced_3h_tsr_3h_196507-196507.nc"
      - "atm_reduced_3h_tsr_3h_196508-196508.nc"
      - "atm_reduced_3h_tsr_3h_196509-196509.nc"
      - "atm_reduced_3h_tsr_3h_196510-196510.nc"
      - "atm_reduced_3h_tsr_3h_196511-196511.nc"
      - "atm_reduced_3h_tsr_3h_196512-196512.nc"
      # 1966
      - "atm_reduced_3h_tsr_3h_196601-196601.nc"
      - "atm_reduced_3h_tsr_3h_196602-196602.nc"
      - "atm_reduced_3h_tsr_3h_196603-196603.nc"
      - "atm_reduced_3h_tsr_3h_196604-196604.nc"
      - "atm_reduced_3h_tsr_3h_196605-196605.nc"
      - "atm_reduced_3h_tsr_3h_196606-196606.nc"
      - "atm_reduced_3h_tsr_3h_196607-196607.nc"
      - "atm_reduced_3h_tsr_3h_196608-196608.nc"
      - "atm_reduced_3h_tsr_3h_196609-196609.nc"
      - "atm_reduced_3h_tsr_3h_196610-196610.nc"
      - "atm_reduced_3h_tsr_3h_196611-196611.nc"
      - "atm_reduced_3h_tsr_3h_196612-196612.nc"
      # 1967
      - "atm_reduced_3h_tsr_3h_196701-196701.nc"
      - "atm_reduced_3h_tsr_3h_196702-196702.nc"
      - "atm_reduced_3h_tsr_3h_196703-196703.nc"
      - "atm_reduced_3h_tsr_3h_196704-196704.nc"
      - "atm_reduced_3h_tsr_3h_196705-196705.nc"
      - "atm_reduced_3h_tsr_3h_196706-196706.nc"
      - "atm_reduced_3h_tsr_3h_196707-196707.nc"
      - "atm_reduced_3h_tsr_3h_196708-196708.nc"
      - "atm_reduced_3h_tsr_3h_196709-196709.nc"
      - "atm_reduced_3h_tsr_3h_196710-196710.nc"
      - "atm_reduced_3h_tsr_3h_196711-196711.nc"
      - "atm_reduced_3h_tsr_3h_196712-196712.nc"
      # 1968
      - "atm_reduced_3h_tsr_3h_196801-196801.nc"
      - "atm_reduced_3h_tsr_3h_196802-196802.nc"
      - "atm_reduced_3h_tsr_3h_196803-196803.nc"
      - "atm_reduced_3h_tsr_3h_196804-196804.nc"
      - "atm_reduced_3h_tsr_3h_196805-196805.nc"
      - "atm_reduced_3h_tsr_3h_196806-196806.nc"
      - "atm_reduced_3h_tsr_3h_196807-196807.nc"
      - "atm_reduced_3h_tsr_3h_196808-196808.nc"
      - "atm_reduced_3h_tsr_3h_196809-196809.nc"
      - "atm_reduced_3h_tsr_3h_196810-196810.nc"
      - "atm_reduced_3h_tsr_3h_196811-196811.nc"
      - "atm_reduced_3h_tsr_3h_196812-196812.nc"
      # 1969
      - "atm_reduced_3h_tsr_3h_196901-196901.nc"
      - "atm_reduced_3h_tsr_3h_196902-196902.nc"
      - "atm_reduced_3h_tsr_3h_196903-196903.nc"
      - "atm_reduced_3h_tsr_3h_196904-196904.nc"
      - "atm_reduced_3h_tsr_3h_196905-196905.nc"
      - "atm_reduced_3h_tsr_3h_196906-196906.nc"
      - "atm_reduced_3h_tsr_3h_196907-196907.nc"
      - "atm_reduced_3h_tsr_3h_196908-196908.nc"
      - "atm_reduced_3h_tsr_3h_196909-196909.nc"
      - "atm_reduced_3h_tsr_3h_196910-196910.nc"
      - "atm_reduced_3h_tsr_3h_196911-196911.nc"
      - "atm_reduced_3h_tsr_3h_196912-196912.nc"
