# UFTP Transfer Configuration for Dunkelflaute Analysis
# Transfer tsr (solar radiation) files for TCo1279-DART-2080C
# Source: Olaf /arch/bm1344/awicm3/TCo1279-DART-2080C/outdata/oifs
# Destination: Levante /work/ab0995/ICCP_AWI_hackthon_2025/TCo1279-DART-2080C/outdata/oifs
# Years: 2080-2090
# Variable: tsr
# Generated: Mon Dec 15 14:17:09 CET 2025

transfers:
  - name: "TCo1279-DART-2080C tsr 2080-2090 from olaf"
    local_base: "/arch/bm1344/awicm3/TCo1279-DART-2080C/outdata/oifs"
    remote_dir: "/work/ab0995/ICCP_AWI_hackthon_2025/TCo1279-DART-2080C/outdata/oifs"
    files:
      # 2080
      - "atm_reduced_3h_tsr_3h_208001-208001.nc"
      - "atm_reduced_3h_tsr_3h_208002-208002.nc"
      - "atm_reduced_3h_tsr_3h_208003-208003.nc"
      - "atm_reduced_3h_tsr_3h_208004-208004.nc"
      - "atm_reduced_3h_tsr_3h_208005-208005.nc"
      - "atm_reduced_3h_tsr_3h_208006-208006.nc"
      - "atm_reduced_3h_tsr_3h_208007-208007.nc"
      - "atm_reduced_3h_tsr_3h_208008-208008.nc"
      - "atm_reduced_3h_tsr_3h_208009-208009.nc"
      - "atm_reduced_3h_tsr_3h_208010-208010.nc"
      - "atm_reduced_3h_tsr_3h_208011-208011.nc"
      - "atm_reduced_3h_tsr_3h_208012-208012.nc"
      # 2081
      - "atm_reduced_3h_tsr_3h_208101-208101.nc"
      - "atm_reduced_3h_tsr_3h_208102-208102.nc"
      - "atm_reduced_3h_tsr_3h_208103-208103.nc"
      - "atm_reduced_3h_tsr_3h_208104-208104.nc"
      - "atm_reduced_3h_tsr_3h_208105-208105.nc"
      - "atm_reduced_3h_tsr_3h_208106-208106.nc"
      - "atm_reduced_3h_tsr_3h_208107-208107.nc"
      - "atm_reduced_3h_tsr_3h_208108-208108.nc"
      - "atm_reduced_3h_tsr_3h_208109-208109.nc"
      - "atm_reduced_3h_tsr_3h_208110-208110.nc"
      - "atm_reduced_3h_tsr_3h_208111-208111.nc"
      - "atm_reduced_3h_tsr_3h_208112-208112.nc"
      # 2082
      - "atm_reduced_3h_tsr_3h_208201-208201.nc"
      - "atm_reduced_3h_tsr_3h_208202-208202.nc"
      - "atm_reduced_3h_tsr_3h_208203-208203.nc"
      - "atm_reduced_3h_tsr_3h_208204-208204.nc"
      - "atm_reduced_3h_tsr_3h_208205-208205.nc"
      - "atm_reduced_3h_tsr_3h_208206-208206.nc"
      - "atm_reduced_3h_tsr_3h_208207-208207.nc"
      - "atm_reduced_3h_tsr_3h_208208-208208.nc"
      - "atm_reduced_3h_tsr_3h_208209-208209.nc"
      - "atm_reduced_3h_tsr_3h_208210-208210.nc"
      - "atm_reduced_3h_tsr_3h_208211-208211.nc"
      - "atm_reduced_3h_tsr_3h_208212-208212.nc"
      # 2083
      - "atm_reduced_3h_tsr_3h_208301-208301.nc"
      - "atm_reduced_3h_tsr_3h_208302-208302.nc"
      - "atm_reduced_3h_tsr_3h_208303-208303.nc"
      - "atm_reduced_3h_tsr_3h_208304-208304.nc"
      - "atm_reduced_3h_tsr_3h_208305-208305.nc"
      - "atm_reduced_3h_tsr_3h_208306-208306.nc"
      - "atm_reduced_3h_tsr_3h_208307-208307.nc"
      - "atm_reduced_3h_tsr_3h_208308-208308.nc"
      - "atm_reduced_3h_tsr_3h_208309-208309.nc"
      - "atm_reduced_3h_tsr_3h_208310-208310.nc"
      - "atm_reduced_3h_tsr_3h_208311-208311.nc"
      - "atm_reduced_3h_tsr_3h_208312-208312.nc"
      # 2084
      - "atm_reduced_3h_tsr_3h_208401-208401.nc"
      - "atm_reduced_3h_tsr_3h_208402-208402.nc"
      - "atm_reduced_3h_tsr_3h_208403-208403.nc"
      - "atm_reduced_3h_tsr_3h_208404-208404.nc"
      - "atm_reduced_3h_tsr_3h_208405-208405.nc"
      - "atm_reduced_3h_tsr_3h_208406-208406.nc"
      - "atm_reduced_3h_tsr_3h_208407-208407.nc"
      - "atm_reduced_3h_tsr_3h_208408-208408.nc"
      - "atm_reduced_3h_tsr_3h_208409-208409.nc"
      - "atm_reduced_3h_tsr_3h_208410-208410.nc"
      - "atm_reduced_3h_tsr_3h_208411-208411.nc"
      - "atm_reduced_3h_tsr_3h_208412-208412.nc"
      # 2085
      - "atm_reduced_3h_tsr_3h_208501-208501.nc"
      - "atm_reduced_3h_tsr_3h_208502-208502.nc"
      - "atm_reduced_3h_tsr_3h_208503-208503.nc"
      - "atm_reduced_3h_tsr_3h_208504-208504.nc"
      - "atm_reduced_3h_tsr_3h_208505-208505.nc"
      - "atm_reduced_3h_tsr_3h_208506-208506.nc"
      - "atm_reduced_3h_tsr_3h_208507-208507.nc"
      - "atm_reduced_3h_tsr_3h_208508-208508.nc"
      - "atm_reduced_3h_tsr_3h_208509-208509.nc"
      - "atm_reduced_3h_tsr_3h_208510-208510.nc"
      - "atm_reduced_3h_tsr_3h_208511-208511.nc"
      - "atm_reduced_3h_tsr_3h_208512-208512.nc"
      # 2086
      - "atm_reduced_3h_tsr_3h_208601-208601.nc"
      - "atm_reduced_3h_tsr_3h_208602-208602.nc"
      - "atm_reduced_3h_tsr_3h_208603-208603.nc"
      - "atm_reduced_3h_tsr_3h_208604-208604.nc"
      - "atm_reduced_3h_tsr_3h_208605-208605.nc"
      - "atm_reduced_3h_tsr_3h_208606-208606.nc"
      - "atm_reduced_3h_tsr_3h_208607-208607.nc"
      - "atm_reduced_3h_tsr_3h_208608-208608.nc"
      - "atm_reduced_3h_tsr_3h_208609-208609.nc"
      - "atm_reduced_3h_tsr_3h_208610-208610.nc"
      - "atm_reduced_3h_tsr_3h_208611-208611.nc"
      - "atm_reduced_3h_tsr_3h_208612-208612.nc"
      # 2087
      - "atm_reduced_3h_tsr_3h_208701-208701.nc"
      - "atm_reduced_3h_tsr_3h_208702-208702.nc"
      - "atm_reduced_3h_tsr_3h_208703-208703.nc"
      - "atm_reduced_3h_tsr_3h_208704-208704.nc"
      - "atm_reduced_3h_tsr_3h_208705-208705.nc"
      - "atm_reduced_3h_tsr_3h_208706-208706.nc"
      - "atm_reduced_3h_tsr_3h_208707-208707.nc"
      - "atm_reduced_3h_tsr_3h_208708-208708.nc"
      - "atm_reduced_3h_tsr_3h_208709-208709.nc"
      - "atm_reduced_3h_tsr_3h_208710-208710.nc"
      - "atm_reduced_3h_tsr_3h_208711-208711.nc"
      - "atm_reduced_3h_tsr_3h_208712-208712.nc"
      # 2088
      - "atm_reduced_3h_tsr_3h_208801-208801.nc"
      - "atm_reduced_3h_tsr_3h_208802-208802.nc"
      - "atm_reduced_3h_tsr_3h_208803-208803.nc"
      - "atm_reduced_3h_tsr_3h_208804-208804.nc"
      - "atm_reduced_3h_tsr_3h_208805-208805.nc"
      - "atm_reduced_3h_tsr_3h_208806-208806.nc"
      - "atm_reduced_3h_tsr_3h_208807-208807.nc"
      - "atm_reduced_3h_tsr_3h_208808-208808.nc"
      - "atm_reduced_3h_tsr_3h_208809-208809.nc"
      - "atm_reduced_3h_tsr_3h_208810-208810.nc"
      - "atm_reduced_3h_tsr_3h_208811-208811.nc"
      - "atm_reduced_3h_tsr_3h_208812-208812.nc"
      # 2089
      - "atm_reduced_3h_tsr_3h_208901-208901.nc"
      - "atm_reduced_3h_tsr_3h_208902-208902.nc"
      - "atm_reduced_3h_tsr_3h_208903-208903.nc"
      - "atm_reduced_3h_tsr_3h_208904-208904.nc"
      - "atm_reduced_3h_tsr_3h_208905-208905.nc"
      - "atm_reduced_3h_tsr_3h_208906-208906.nc"
      - "atm_reduced_3h_tsr_3h_208907-208907.nc"
      - "atm_reduced_3h_tsr_3h_208908-208908.nc"
      - "atm_reduced_3h_tsr_3h_208909-208909.nc"
      - "atm_reduced_3h_tsr_3h_208910-208910.nc"
      - "atm_reduced_3h_tsr_3h_208911-208911.nc"
      - "atm_reduced_3h_tsr_3h_208912-208912.nc"
      # 2090
      - "atm_reduced_3h_tsr_3h_209001-209001.nc"
      - "atm_reduced_3h_tsr_3h_209002-209002.nc"
      - "atm_reduced_3h_tsr_3h_209003-209003.nc"
      - "atm_reduced_3h_tsr_3h_209004-209004.nc"
      - "atm_reduced_3h_tsr_3h_209005-209005.nc"
      - "atm_reduced_3h_tsr_3h_209006-209006.nc"
      - "atm_reduced_3h_tsr_3h_209007-209007.nc"
      - "atm_reduced_3h_tsr_3h_209008-209008.nc"
      - "atm_reduced_3h_tsr_3h_209009-209009.nc"
      - "atm_reduced_3h_tsr_3h_209010-209010.nc"
      - "atm_reduced_3h_tsr_3h_209011-209011.nc"
      - "atm_reduced_3h_tsr_3h_209012-209012.nc"
